### ISSUE TITLE
Route is not defined

### ISSUE THREAD

**Issue by dalchand** [kahmali/meteor-restivus#65]
Hi,

I'm getting this error on my console log

Uncaught ReferenceError: Route is not defined                        restivus.coffee:70

**Comment by kahmali** [comment]
Can you please provide steps to reproduce the error? I'll need as much information as possible to help you. Code examples are always useful.

**Comment by dalchand** [comment]
Will create one repo on github and share it with you. It's not happening on the machine I am working right now.

**Comment by dalchand** [comment]
https://github.com/dalchand/rest-test

**Comment by dalchand** [comment]
It appears the problem is because I have defined Restivus.configure in commons.js which is outside client and server folder. But since I'm using client side Iron Router isn't that what I should be doing?

**Comment by kahmali** [comment]
No, you should configure and declare your Restivus routes on the server. I attempted to give users that weren't using Iron Router on the client a means of disabling Iron Router client side (#24), and that's the only configuration option (`useClientRouter`) that would require anything to be run on the client. But even though it worked locally, it didn't work after publishing. Fortunately, #46 resolved that issue and many more by removing the Iron Router dependency (leaving you free to use any router of your choosing client- or server-side alongside Restivus). That will be released in the next major update, v0.7.0. 

Luckily for you, you're already using Iron Router on the client, so you can omit the last config option (which was misspelled and therefore would have been ignored anyway), and setup Restivus on the server where it belongs. Let me know if that resolves this. Sorry for the confusion. I'll be sure to make it very clear that this is a server-only package in v0.7.0+. Thanks for reporting the issue!

**Comment by dalchand** [comment]
Sorry my bad ... got it.

**Comment by kahmali** [comment]
No problem! Let me know if you run into any other issues.

**Comment by ced-qc-ca** [comment]
@kahmali I am building a project using Angular on client side and custom REST routes on server side. How Can I patch this issue until the routing engine is swaped? Thanks!

**Comment by kahmali** [comment]
Oh wow. My bad. I was waiting to hear back from @nicoonee on #67 and I completely forgot to just bump the version and publish that fix. It's all set. I'll publish it now. I'll let you know once it's up. So sorry about that! I've been tied up with a few other projects but I hope to give Restivus a ton of love soon.

**Comment by kahmali** [comment]
Scratch what I just said. I did release v0.6.6 with this fix. This issue should be resolved without any patching. What exactly are you referring to? The iron:router replacement? You can definitely grab the latest on the `0.7.0` branch for an early release, if that's what you're asking.

**Comment by ced-qc-ca** [comment]
I am referring to v0.6.6. I tried setting up Restivus using useClientRouter = false like you mentionned, but it doesn't solve the problem. Iron-Router is still provided on client side. Also, on a different issue, the notFoundTemplate is rendered #24 , I still reproduce it. I can provide more details about my setup on that issue #

**Comment by kahmali** [comment]
When you say Iron router is provided on the client side, is that the issue you're having, **or are you referring specifically to the error discussed in _this_ issue**? Because if your issue is that you want Iron Router removed, you need to checkout an early release branch as I suggested (0.7.0). The same goes for #24 (as I [explained in that thread](https://github.com/kahmali/meteor-restivus/issues/24#issuecomment-98328215)).

**Comment by ced-qc-ca** [comment]
Late response, but better late than never. :) I did as you suggested and it did the job.

**Comment by kahmali** [comment]
Awesome! Glad that did the trick! Thanks for verifying the fix.
